Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName

Outputs:
  RegionalDomainName:
    Value: !GetAtt S3Bucket.RegionalDomainName
