name: Deploy AWS Resources with OIDC Authentication

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up AWS OIDC Authentication
    - name: Configure AWS credentials for Terraform
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    # Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7  # Specify your desired Terraform version

    # Step 4: Terraform Initialization
    - name: Initialize Terraform
      run: terraform init

    # Step 5: Terraform Plan (Optional: Check what will be created/modified)
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Apply Terraform Plan (to create/update resources)
    - name: Terraform Apply
      run: terraform apply -auto-approve
